# Generated by Django 5.1.1 on 2024-09-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_moodentry_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pid',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=255),
        ),
    ]
